Templates/edit templates
rizalilhamm/flask-crude pull request #8
Opened 2021-03-23 09:04 UTC by rizalilhamm

2021-03-23 10:01 UTC, iwansyahp requested changes

2021-03-23 10:01 UTC, iwansyahp commented on app/__init__.py
> +from app.user import user
from app.models import User
from app.user import user

apa beda user dari app.user dan User dari app.models?

2021-03-23 10:01 UTC, iwansyahp commented on app/auth.py
> +# @app.route('/<string:name>')
Kenapa di-komentar?

2021-03-23 10:01 UTC, iwansyahp commented on app/models.py
> +    about = db.Column(db.String(140))
Beri komentar apa kegunaan masing-masing kolom pada table

2021-03-23 10:01 UTC, iwansyahp commented on app/templates/content.html
> +                                </a>
buang space di akhir

2021-03-23 10:01 UTC, iwansyahp commented on app/user/user.py
> +
ubah nama file dan folder jadi `user_controller` atau `user_module` untuk membedakannya dengan User pada module. Perhatikan arsitektur apa yang digunakan, MVC/MVT atau lainnya

2021-03-23 10:01 UTC, iwansyahp commented on app/user/user.py
> +    form = request.form
ini tidak perlu

2021-03-23 10:01 UTC, iwansyahp commented on app/user/user.py
> +    name = form.get('name')
ubah jadi `name = request.form.get('name')` di sini dan di variable lainnya setelah menghapus `form = request.form`

2021-03-23 10:01 UTC, iwansyahp commented on app/user/user.py
> +        flash("Profile berhasil di update")
diupdate, bukan di update.

2021-03-23 10:01 UTC, iwansyahp commented on app/user/user.py
> +            flash("Masih ada yang salah")
Ganti pesan menjadi `password lama salah, berikan pesan secara spesifik`

2021-03-23 10:01 UTC, iwansyahp commented on app/user/user.py
> +            flash("Password baru/lama masih ada yang kosong")
Berikan pesan yang lebih mewakili kesalahan yang terjadi, di sini adalah kesalahan password baru dan konfirmasinya masih salah

2021-03-23 10:01 UTC, iwansyahp commented on app/views.py
> +    return "Turn the Button"
Kenapa `Turn the Button`?

2021-03-25 06:16 UTC, rizalilhamm commented on app/auth.py
> +# @app.route('/<string:name>')
the function has moved to app.auth module

2021-03-25 07:13 UTC, rizalilhamm commented on app/__init__.py
> +from app.user import user
app.models merupakan class dari User models, sedangkan  app.user adalah modul yang berisi semua tugas yang berhubungan dengan user saja, seperti update profile, ganti nama, ganti password etc.

2021-03-25 07:14 UTC, rizalilhamm commented on app/models.py
> +    about = db.Column(db.String(140))
Done

2021-03-25 07:16 UTC, rizalilhamm commented on app/templates/content.html
> +                                </a>
Done

2021-03-25 07:27 UTC, rizalilhamm commented on app/user/user.py
> +    form = request.form
Done

2021-03-25 07:28 UTC, rizalilhamm commented on app/user/user.py
> +    name = form.get('name')
Done

2021-03-25 07:28 UTC, rizalilhamm commented on app/user/user.py
> +        flash("Profile berhasil di update")
Done

2021-03-25 18:20 UTC, rizalilhamm commented on app/__init__.py
> +from app.user import user
Structur akan diperbaiki nanti

2021-03-25 18:41 UTC, rizalilhamm commented on app/user/user.py
> +            flash("Password baru/lama masih ada yang kosong")
Done

2021-03-25 18:41 UTC, rizalilhamm commented on app/views.py
> +    return "Turn the Button"
Function deleted

2021-03-25 18:41 UTC, rizalilhamm commented on app/user/user.py
> +            flash("Masih ada yang salah")
Done

2021-03-25 19:47 UTC, rizalilhamm commented on app/user/user.py
> +
Done

2021-03-25 19:57 UTC, closed without merging